[package]
name = "wgame-gfx-texture"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
wgame-gfx.workspace = true
wgame-image.workspace = true
wgame-shader.workspace = true
wgpu.workspace = true
bytemuck.workspace = true
euclid.workspace = true
glam.workspace = true
rgb.workspace = true
half.workspace = true
hashbrown.workspace = true
thiserror.workspace = true
futures.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys.workspace = true
wasm-bindgen-futures.workspace = true
web-sys = { workspace = true, features = ["Window"] }
web-time.workspace = true
