#!/usr/bin/env bash
# Build the gallery and browser examples without changing source HTML files.
set -euo pipefail

if (( $# > 2 )); then
  echo "Usage: $0 [public-url=/wgame/] [output-dir=target/pages]" >&2
  exit 2
fi

repo=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
public_url=${1:-/wgame/}
output=${2:-"$repo/target/pages"}
trunk=${TRUNK:-trunk}
public_url=${public_url%/}/

if [[ $public_url != /* || $public_url == *'?'* || $public_url == *'#'* ]]; then
  echo "public-url must be an absolute URL path such as /wgame/." >&2
  exit 2
fi
command -v "$trunk" >/dev/null || {
  echo "Install Trunk with: cargo install trunk --locked" >&2
  exit 1
}
if ! rustup target list --installed | grep -qx wasm32-unknown-unknown; then
  echo "Install the wasm target with: rustup target add wasm32-unknown-unknown" >&2
  exit 1
fi

mkdir -p "$output"
output=$(cd "$output" && pwd)
if [[ -n $(ls -A "$output") && ! -f $output/.wgame-pages ]]; then
  echo "Refusing to replace an output directory not generated by this script: $output" >&2
  exit 2
fi

staging=$(mktemp -d "${TMPDIR:-/tmp}/wgame-pages.XXXXXX")
trap 'rm -rf "$staging"' EXIT
mkdir -p "$staging/site/examples"
cp "$repo/site/"{index.html,styles.css,favicon.svg} "$staging/site/"
touch "$staging/site/.nojekyll" "$staging/site/.wgame-pages"

# Trunk resolves Rust asset hrefs relative to the external wrapper directory.
manifest=$(realpath --relative-to="$staging" "$repo/wgame-examples/Cargo.toml")
manifest=${manifest//&/\&amp;}
manifest=${manifest//\"/\&quot;}
manifest=${manifest//</\&lt;}
manifest=${manifest//>/\&gt;}

cd "$repo/wgame-examples"
while IFS='|' read -r bin slug title; do
  echo "Building $title at ${public_url}examples/$slug/"
  wrapper=$(<"$repo/site/demo.html")
  wrapper=${wrapper//@MANIFEST@/$manifest}
  wrapper=${wrapper//@BIN@/$bin}
  wrapper=${wrapper//@TITLE@/$title}
  printf '%s\n' "$wrapper" > "$staging/$slug.html"
  NO_COLOR=true "$trunk" build "$staging/$slug.html" \
    --release --locked --no-default-features --features web \
    --public-url "${public_url}examples/$slug/" \
    --html-output index.html --dist "$staging/site/examples/$slug"
done <<'EXAMPLES'
playground|playground|Playground
polylines|polylines|Polylines
events|events|On-demand events
viewports|viewports|Viewports
render_textures|render-textures|Render textures
EXAMPLES

# Only replace a recognized build output, after every example succeeds.
if [[ -f $output/.wgame-pages ]]; then
  rm -rf "$output/examples"
fi
cp -a "$staging/site/." "$output/"
echo "Built the wgame gallery in $output (public URL: $public_url)"
