[package]
name = "wgame-text"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
wgame-gfx.workspace = true
wgpu.workspace = true
glyphon = "0.9.0"
rgb.workspace = true
